### ISSUE TITLE
Patch causes game to crash between levels when applied

### ISSUE THREAD

**Issue by Candlemass** [mipek/darkxl-fix#1] opened 2020-12-18 11:01 UTC
Hello,

When this patch is applied and the game reads "Alpha 9.50 DarkFX" on the main menu confirming that it's active the game crashes as soon as you click the "next mission" button between levels. I have confirmed that the patch is the cause of the problem as this does not occur when I remove the patch files from the DarkXL directory and the games main menu displays the default "Alpha Build 9.50". This also occurs whether or not the "Windows XP SP3" compatibility box is applied for the darkxl.exe file that executes the DarkXL launcher as I have read else where that this apparently "fixes" the problem.

Image of the error message that occurs when the game crashes:
https://i.postimg.cc/2jTX7PnZ/Error.jpg

Windows 7 x86 OS machine.

**Comment by mipek** [comment] 2021-03-27 22:02
Thanks for reporting this, it should be fixed now!

**Comment by Candlemass** [comment] 2021-04-13 06:18
Not sure why this is marked as fixed. Just tried out the new patch and the behavior is exactly the same. The game crashes immediately after completing the first level and selecting next from the menu.

**Comment by mipek** [comment] 2021-04-13 07:04
What text is being displayed in the main menu (bottom right corner)? Is the new patch loaded correctly?

**Comment by Candlemass** [comment] 2021-04-18 01:49
As I already stated it's with the new patch.

I have no idea if disabling other fixes will correct the issue but if the patch only works for specific bugs and not all of them then what's the point? You're just recreating one problem to fix another...

I deleted the patch and won't have time to mess around with this again until probably next weekend.

I will do my best to report back then.

**Comment by mipek** [comment] 2021-04-18 16:08
> I have no idea if disabling other fixes will correct the issue but if the patch only works for specific bugs and not all of them then what's the point? You're just recreating one problem to fix another...

I am unable to reproduce the crashing on my system with the latest patch. I asked if the game still crashes if both fixes are disabled to get a better idea why it's crashing (as I can't test it on my own). I'm currently in the process of finding some old hardware to run Windows 7 x86 to reproduce the crash.

**Comment by mipek** [comment] 2021-04-18 20:35
I just installed Windows 7 x86 on a old box and I am still unable to reproduce the crash.
It's a clean installation with just DirectX9, OpenAL32 and Visual Studio Redistributable (2019) installed.

**Comment by mipek** [comment] 2021-08-24 07:06
Closing because I can't reproduce the crash. Feel free to comment on this issue and I'll reopen.

**Closed by mipek** 2021-08-24 07:06 UTC
